name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['lint', 'type:check', 'build']
    steps:
      - name: Checkout repository
        uses: actions/checkout@4

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/pnpm-setup-node

      - name: install dependency
        run: pnpm install --frozon-lockfile

      - name: Run pnpm command
        run: pnpm ${{ matrix.command }}
